//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPrototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appliance
    {
        public Appliance()
        {
            this.Skills = new HashSet<Skill>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public short MinimumCrewCount { get; set; }
        public short MaximumCrewCount { get; set; }
    
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
