//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPrototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class LT_UnavailabilityReason
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public string ColourHex { get; set; }
        public string Icon { get; set; }
        public string Reason { get; set; }
    }
}
