//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkPrototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfflineHour
    {
        public int Id { get; set; }
        public System.Guid UnavailabilityId { get; set; }
        public int OfflineHourReasonId { get; set; }
        public System.Guid ApplianceId { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public System.Guid AuditCreatedBy { get; set; }
        public System.DateTime AuditCreatedDate { get; set; }
    }
}
